author:
  url: www.niyasocannizzarophotography.com
  email: niyaso@gmail.com
  name: Niyaso Cannizzaro
color:
  saturation: 0.03689556964673102
  brandStrength: 0.6721895516384393
  rhythmicContrast: 0.12280064052902162
  brandColors:
    - '#36362C'
    - '#5D917D'
    - '#A8AD80'
    - '#E6D4A7'
    - '#825534'
  lightness: 0.6088254316709936
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.727878896985203
typography_spectrum: 0.8601698761340231
name: niyaso cannizzaro photography
